# Generated by Django 4.2.3 on 2023-08-01 16:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intent', '0001_initial'),
        ('subintent', '0001_initial'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intent.intent')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation')),
                ('subintent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subintent.subintent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
