# Generated by Django 4.2.3 on 2023-08-01 16:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suggestion', '0001_initial'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('content', models.JSONField(blank=True, default=dict, help_text='{"language": "en", "content_data": "Some content"}')),
                ('type', models.CharField(choices=[('Widget', 'WIDGET'), ('Text', 'TEXT')], max_length=10)),
                ('input_allowed', models.BooleanField(default=False)),
                ('content_url', models.URLField(blank=True, max_length=256, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation')),
                ('suggestions', models.ManyToManyField(blank=True, to='suggestion.suggestions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
